### ISSUE TITLE
Transparent background on some GIF and PNG images comes out as black

### ISSUE THREAD

**Issue by tomworthington** [ayastreb/bandwidth-hero-proxy#3]
The transparent background on some GIF and PNG images comes out as black, making many buttons hard to read. It would be better if the compression process was skipped for GIFs and PNGs (or at least for small ones, or those with transparent backgrounds).

**Comment by ayastreb** [comment]
The issue here is that Firefox does not support WebP format, so for FF we always convert to JPEG. And JPEG does not have alpha channel, so images with transparent background get black background in JPEG.

The only good solution I could have think of is to skip small PNG/GIF images from compression in FF.
Now the proxy will only compress PNG/GIF images bigger than 100KB in FF.
This should fix the issue with buttons/sprites since they are almost always smaller than 100KB :)
